server:
    port: 8080
    contextPath:

spring:
    profiles:
        active: dev

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/LKMS?useUnicode=true&amp;characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password:

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: true

    redis:
      host: 192.168.99.100
      port: 32768
      default_expire_time: 86400

